export class Log {
  constructor(
    logId,     // will be auto-generated by Firestore
    userId,
    questionId,
    attempts = 0,
    successRate = 0,
    timestamps = [],
    answers = {
      upper: null,
      lower: null,
      date: new Date()
    }
  ) {
    this.logId = logId;
    this.userId = userId;
    this.questionId = questionId;
    this.attempts = attempts;
    this.successRate = successRate;
    this.timestamps = timestamps;
    this.answers = answers;
  }
}

export default Log;